### ISSUE TITLE
"vc ta de brincadeira"

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#10]
What should we do?

![screen shot 2016-06-30 at 9 44 46 am](https://cloud.githubusercontent.com/assets/7760/16488535/5e5c8a24-3ea7-11e6-8b04-55b1549b5a60.png)

**Comment by GabrielSoga** [comment]
This question really depends on the context.
Although, all the questions that we aren't sure of the answer may be given #2 treatment

**Comment by fczuardi** [comment]
closing this as duplicate of #14 feel free to reopen it if that's not the case
