### ISSUE TITLE
Bigode does not answer properly when he is called only by his name

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#12]
**Current behavior:**
Bigode does not answer properly when he is called only by his name as in the following example:

![img_0233](https://cloud.githubusercontent.com/assets/9004719/16488910/4bed444e-3ea9-11e6-9266-2f664a8faf97.PNG)

**Expected behavior:**
To greet the user and offer some help.

**Comment by GabrielSoga** [comment]
dupe of #6
