### ISSUE TITLE
Differ Close-Messages and Thank-Messages

### ISSUE THREAD

**Issue by GabrielSoga** [calamar-io/calamarcopollo#13]
This is the current behavior:
![close](https://cloud.githubusercontent.com/assets/19688935/16489106/49c95008-3eaa-11e6-9dde-44507e1e80ad.png)

The suggestion is to create a route only for "Thank you" messages, which are currently being answered as Close Messages (and leaving those for "bye bye" only)

**Comment by fczuardi** [comment]
if we go on that route, should we also wipe context #1 on "thank you"s?

**Comment by GabrielSoga** [comment]
This need more test and investigation, but at first sight yes
