### ISSUE TITLE
expect higher confidence on places entities before assuming it is a place

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#14]
related with #8 

some examples of low confidence places entities that we are currently accepting in pollo's code:

![screen shot 2016-06-30 at 10 06 34 am](https://cloud.githubusercontent.com/assets/7760/16489154/935f8624-3eaa-11e6-9b8d-8783bff6629c.png)

![screen shot 2016-06-30 at 10 02 54 am](https://cloud.githubusercontent.com/assets/7760/16489176/b4f924de-3eaa-11e6-9026-58dd4823985f.png)

![screen shot 2016-06-30 at 9 44 46 am](https://cloud.githubusercontent.com/assets/7760/16489181/be7a7486-3eaa-11e6-85ac-10d238716276.png)

![screen shot 2016-06-29 at 6 12 00 pm](https://cloud.githubusercontent.com/assets/7760/16489184/c9326b5e-3eaa-11e6-869f-65b5561bcfe5.png)

**Comment by GabrielSoga** [comment]
How low are those?

**Comment by fczuardi** [comment]
Destination "lá" = 0.7700059824513874
```
{"text":"vish. procura dia 29 pra la","entities":{"datetime":[{"_body":"dia 29","confidence":0.92979596695363,"_start":14,"_end":20,"_entity":"datetime","type":"value","value":"2016-07-29T00:00:00.000-03:00","grain":"day","values":[{"type":"value","value":"2016-07-29T00:00:00.000-03:00","grain":"day"},{"type":"value","value":"2016-08-29T00:00:00.000-03:00","grain":"day"},{"type":"value","value":"2016-09-29T00:00:00.000-03:00","grain":"day"}]}],"destination":[{"_body":"la","confidence":0.7700059824513874,"_start":25,"_end":27,"_role":"destination","_entity":"places","type":"value","value":"la","suggested":true}]}}
```

Origin "brincadeira" = 0.8864293202273743
```
{"text":"vc ta de brincadeira","entities":{"origin":[{"_body":"brincadeira","confidence":0.8864293202273743,"_start":9,"_end":20,"_role":"origin","_entity":"places","type":"value","value":"brincadeira","suggested":true}],"trip":[{"confidence":0.51451941954371,"_entity":"trip","value":"info"}]}}
```

Destination "ha" = 0.4910467677495223
```
{"text":"ha ha ha ha","entities":{"destination":[{"_body":"ha","confidence":0.4910467677495223,"_start":9,"_end":11,"_role":"destination","_entity":"places","type":"value","value":"ha","suggested":true}]}}
```

**Comment by fczuardi** [comment]
The current threshold is 0.7, but the main problem is that it is currently only applied for statements with trip info intent. We should be enforcing it also on the statements without trip intent in order to match, but currently the code don't do that. This is a bug.

**Comment by fczuardi** [comment]
As comment on https://github.com/calamar-io/calamarcopollo/issues/8#issuecomment-229652935 we should think about what to do when the entity has low confidence, but fuzzy-search-matches a known city of the local slugs db.

@vstabile suggested on Telegram that we cold accept lowest wit confidence for higher popular cities, but maybe that is a different bug.

Do we have a bug for the "Estaca Zero, PI" yet? :)

**Comment by GabrielSoga** [comment]
As discussed with@fczuardi, we shall import the city list on wit, and then discard all low-confidence matches

 about Estaca Zero now we do, at #6 (comment) ;)

**Comment by isadoramariamendes** [comment]
The same issue is happening when the user provide state initials. I think in this case the confidence should be higher yet.
![img_0248](https://cloud.githubusercontent.com/assets/9004719/16527533/d3744d2e-3f8d-11e6-8c49-8b499aec5a27.PNG)

**Comment by fczuardi** [comment]
one extra example:

![screen shot 2016-07-06 at 4 22 16 pm](https://cloud.githubusercontent.com/assets/7760/16631506/e08a0fd8-4395-11e6-8b5e-6c66e1099de3.png)
