### ISSUE TITLE
[Suggestion/Bug] Reset user search trip 

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#15]
Firstly, bigode cloudn't help locating "California". After a while, we talked a lot and we "we finish" the conversation since I asked for help, he provided some information on how he could help me and so we thanked each other. 
So, I started a new conversation and I asked for a joke. Instead of telling me a joke, he provided the results of a trip from California To Pindamonhangaba...
Check the print:

![img_0234](https://cloud.githubusercontent.com/assets/9004719/16489143/83cc0e08-3eaa-11e6-8152-dd8f31b0f9ef.PNG)
It would be nice to reset the users' trip input after a while and check why he didn't accept California as input in the beginning and after some minutes he just used the "invalid input" as Destination.

**Comment by GabrielSoga** [comment]
related to #1

**Comment by GabrielSoga** [comment]
I didin't understand the "check" suggestion. Can you explain?

**Comment by isadoramariamendes** [comment]
Actually, the suggestion is just the "reset" feature... But it would be great the verify what happened, I mean... Why it didn't accept California in the first moment and after a while it just used California as destination...?

**Comment by GabrielSoga** [comment]
Oh, I understand now. Let's reset the context after getting a fail-query then!
I'll close this as a dupe, but let's keep your suggestion

**Comment by fczuardi** [comment]
We do accept California:

![screen shot 2016-06-30 at 10 48 11 am](https://cloud.githubusercontent.com/assets/7760/16490489/4098cb20-3eb0-11e6-92fb-fb831fe77468.png)

😺
