### ISSUE TITLE
command and place in the same statement

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#18]
![screen shot 2016-06-30 at 2 28 40 pm](https://cloud.githubusercontent.com/assets/7760/16497801/2a9ff158-3ecf-11e6-829d-0330e797e010.png)

**Comment by fczuardi** [comment]
see https://github.com/calamar-io/calamarcopollo/issues/6#issuecomment-229719292 for an example of how this reflects on the current behavior of the bot

**Comment by GabrielSoga** [comment]
#21 must fix this

**Comment by fczuardi** [comment]
fixed with the fix for #21
