### ISSUE TITLE
Change or deprecate unknown-routes answer

### ISSUE THREAD

**Issue by GabrielSoga** [calamar-io/calamarcopollo#2]
The answers are getting annoying and spammy when the bot doesn't understand a query
![apologies](https://cloud.githubusercontent.com/assets/19688935/16475307/cb896648-3e53-11e6-94a2-df1ec90f1f19.png)
We should deprecate those answers, or change them to something more neutral (like a neutral emoji)

**Comment by fczuardi** [comment]
one suggestion: keep the reply for the first unknown route, but also keep track of the latest or 2 latest replies and if there is an unknown recently given, then use the generic neutral answer…

**Comment by GabrielSoga** [comment]
@fczuardi this may work nicely

**Comment by fczuardi** [comment]
just documenting a sample of how this bug manifests itself to the user:

![screen shot 2016-07-04 at 1 53 58 pm](https://cloud.githubusercontent.com/assets/7760/16566867/e086cae2-41ee-11e6-948d-7090093f34ed.png)

**Comment by GabrielSoga** [comment]
I adjusted them on Bigode's Routes to be more assertive: 

```javascript
    debug => `Perdão, não entendi${ debug }`,
    debug => `Desculpe, não estou entendendo${ debug }`,
    debug => `Não entendi 😥${ debug }`,
    debug => `Estou confuso, não entendi..${ debug }`,
    debug => `Pode refrasear, por favor?${ debug }`,
    debug => `Desculpa, perdi esta${ debug }`,
    debug => `Não estou te entendendo${ debug }`
```

**Comment by fczuardi** [comment]
but we still need neutral answers for multiple unknown answers in a row, right?

**Comment by GabrielSoga** [comment]
Those answers are important to indicate typos from the user. At the moment, we can't filter if the query is a typo or is really unknown.
I guess we can keep those like this for the moment. Let's reopen if needed (after some tests)
