### ISSUE TITLE
[Sugesttion] Message reply when user inputs the same city to origin and destination

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#22]
When the user inputs the same city to origin and destination, Bigode keep asking for the destination repeatedly. 
**Example:**
![img_0242](https://cloud.githubusercontent.com/assets/9004719/16510915/d99209ca-3f20-11e6-94cb-b6220ea33067.PNG)

**Easy fix:**
It would be better if he could say something different such as "A cidade de origem e destino precisam ser diferentes. Por favor, digite outro destino ou escreva recomeçar para fazer uma busca diferente."

**Comment by GabrielSoga** [comment]
fixed , same reason to #54
