### ISSUE TITLE
[Sugesttion] Message reply when user inputs a invalid city twice

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#23]
When the user inputs a invalid destination city, Bigode keep asking "E o destino?".
Check in the exemple below **from 11:12 AM on**...
![img_0243](https://cloud.githubusercontent.com/assets/9004719/16524120/25d347c0-3f7d-11e6-9d69-0e491b8ca813.PNG)
It could be improved if when it happens, he could alert the user that he wants a valid destination instead of keep asking "E o destino?" all the time.

**Comment by GabrielSoga** [comment]
Nice! i'll put this in our milestone

**Comment by GabrielSoga** [comment]
After investigation, this is another bug #54 that was already closed 
![california](https://cloud.githubusercontent.com/assets/19688935/16594624/a2d0dfca-42c1-11e6-9781-1c1f3ab5a5cf.png)
And yeah, there IS a california!!
