### ISSUE TITLE
"Vc é uma gata"

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#39]
![screen shot 2016-07-04 at 2 20 57 pm](https://cloud.githubusercontent.com/assets/7760/16567233/91ea4036-41f2-11e6-8f0f-43dd8e7b32c4.png)

![screen shot 2016-07-04 at 2 21 40 pm](https://cloud.githubusercontent.com/assets/7760/16567247/b7efb504-41f2-11e6-87bc-8c86e0f2e09a.png)

**Comment by GabrielSoga** [comment]
Trained and closed for now
