### ISSUE TITLE
Wrong results depending on cities' order input

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#4]
The search results are wrong when the user requests a trip search as the following example:

![img_0226](https://cloud.githubusercontent.com/assets/9004719/16475375/78c1dd4a-3e54-11e6-80ac-be62e9c4abfa.PNG)

I.e., it happens when the user requests "to... from..." instead of the usual "from... to...".

**Comment by fczuardi** [comment]
The current rule for 2 places without role in the same statement, such as:

![screen shot 2016-06-30 at 12 04 35 am](https://cloud.githubusercontent.com/assets/7760/16475620/5d373168-3e56-11e6-81b6-f4337f94f50a.png)

Just assumes that the first is origin and the second destination.

- One possible fix is just to train wit with more examples.
- Another possible fix is to look for "para" and "de" in the code, what might be a slippery slope, but doable.

**Comment by fczuardi** [comment]
after some extra wit training the issue works for me, closing this, feel free to reopen if it fails again for different statements
