### ISSUE TITLE
"Quanto custa uma passagem?" price intent?

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#43]
opening for tracking/discussion about how should we handle this in the future

![screen shot 2016-07-04 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/7760/16567344/0acf79c0-41f4-11e6-9325-b7d0ec94d6ff.png)

**Comment by GabrielSoga** [comment]
related to #3

**Comment by GabrielSoga** [comment]
fixed with faq:preco
![custa](https://cloud.githubusercontent.com/assets/19688935/16599441/b04d0266-42d8-11e6-8610-92ff8ef1e9c3.png)
