### ISSUE TITLE
replace textual short link with a carousel item.

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#53]
This is one of the possibilities of alternatives to the link with full search results after the carousel. the other is to replace the link with a button on fb #52

**Comment by GabrielSoga** [comment]
My suggestion:
Main:
Cometa - 13:00h - R$ 67,35

Secondary:
São Paulo, SP - Tiete -> São Carlos, SP - 3:40min

**Comment by fczuardi** [comment]
I am submitting the first patch that fixes this, but we will need an image to use on that last item, filed #56 for that

**Comment by fczuardi** [comment]
fixed with 4f59e02291584c6292a6068f88f59f209bfe890c
