### ISSUE TITLE
[Trip] Origin role bug

### ISSUE THREAD

**Issue by GabrielSoga** [calamar-io/calamarcopollo#54]
Already investigated, when the query is a single city only, wit is getting as places:origin instead of places 
![originbug](https://cloud.githubusercontent.com/assets/19688935/16587604/e2113998-42a1-11e6-9d05-afaa77d9d07f.png)

Then, you can't set a destination

**Comment by GabrielSoga** [comment]
Issue reopened as happened again:
![rolebug1](https://cloud.githubusercontent.com/assets/19688935/16876533/9053aa92-4a7a-11e6-93c8-acc1d07d5add.png)

![rolebug2](https://cloud.githubusercontent.com/assets/19688935/16876540/93de3d3a-4a7a-11e6-879a-bb07ddabe05d.png)

**Comment by fczuardi** [comment]
fixed on 1.1.1
