### ISSUE TITLE
implement a Persistent menu

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#59]
Now that calamars support this feature, what should the pollo persistent menu contain?

Is this menu the same for pollo and bigode? Do we want to make this persistent menu customisable?

**Comment by GabrielSoga** [comment]
nicely done already!
![persistent](https://cloud.githubusercontent.com/assets/19688935/16634464/3961b238-43a4-11e6-9399-8c830290d779.png)
