### ISSUE TITLE
handle requests for listing the supported cities

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamarcopollo#66]
### Current behavior:

![screen shot 2016-07-05 at 6 16 56 pm](https://cloud.githubusercontent.com/assets/7760/16600355/0a3fe78a-42dd-11e6-91ab-757fc19419de.png)

### Expected behavior:

Listing all the 4 thousands cities is not an option.

If we want to reply to such queries maybe we could use a generic answer at first, and in the future, when we have better ways to filter the places list into something that fits the replies limits (be it the 320 char/reply or the carousel limitations) then we can test different approaches.

This bug is probably related with #24

**Comment by GabrielSoga** [comment]
Related to #24.
I'm currently working on a placeholder fix
